---
name: todo_app_ddd
description: Todo Flutter App based on Domain Driven Design and Firebase
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  another_flushbar:
  auto_route:
  cupertino_icons:
  dartz:
  email_validator:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_bloc:
  freezed_annotation:
  get_it:
  google_sign_in:
  injectable:
  kt_dart:
  rive:
  uuid:

dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_launcher_icons:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  injectable_generator:
  lint:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/ic_launcher3.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/notebook.png
    - assets/animations/movie_recorder_loading.riv
    - assets/
    - assets/icons/
    - assets/animations/
    - assets/images/




