---
name: todo_app_ddd
description: Todo Flutter App based on Domain Driven Design and Firebase
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  another_flushbar:
  cupertino_icons:
  dartz:
  email_validator:
  firebase_auth:
  firebase_core:
  flutter:
    sdk: flutter
  flutter_bloc:
  freezed_annotation:
  get_it:
  google_sign_in:
  injectable:
  uuid:

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter
  freezed:
  injectable_generator:
  lint:

flutter:
  uses-material-design: true
  assets:
    - assets/images/notebook.png
