---
name: todo_app_ddd
description: Todo Flutter App based on Domain Driven Design and Firebase
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^1.1.0
  email_validator: ^2.0.1
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.0.0
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1

dev_dependencies:
  build_runner: ^2.1.7
  freezed: ^1.1.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
