---
name: todo_app_ddd
description: Todo Flutter App based on Domain Driven Design and Firebase
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.4
  dartz: ^0.10.1
  email_validator: ^2.0.1
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  freezed_annotation: ^1.1.0
  get_it: ^7.2.0
  google_sign_in: ^5.2.1
  injectable: ^1.5.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  freezed: ^1.1.0
  injectable_generator: ^1.5.2
  lint: ^1.8.1

flutter:
  uses-material-design: true
